token: /home/prima/prima-gapi-keys/token.json
credentials: /home/prima/prima-gapi-keys/credentials.json
schedules:
  drs: l3dtd0gg4de092kcpkr8upooe8@group.calendar.google.com
  dr: bp557vt3mdtb5geruf640s2mk0@group.calendar.google.com
  cll: 03seevqif5bqhhkqe8iq08idfg@group.calendar.google.com
  bcf: raer55djap80emifh77armcra0@group.calendar.google.com
  ba: hfmqnn9p4q991t4lf5fsmhoqd0@group.calendar.google.com
  social: jsdbh33hq6pv0u7tg8jkddpsa8@group.calendar.google.com
  zad: e3e7uthcopnjeqf8t4tuk449v4@group.calendar.google.com